OptimisedGDBackend:
  availableCommands:
    jpg:
      jpegoptim: '%1$s/jpegoptim -p -m%3$d --strip-all %2$s'
    png:
      optipng: '%s/optipng %s'
      pngcrush: '%s/pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB -ow %s'
      advpng: '%s/advpng -z4 $Filename'
  enabledCommands:
  binDirectory: '/usr/local/bin'
  optimisingQuality: 80
